### ISSUE TITLE
Crashes Notepad++

### ISSUE THREAD

**Issue by Godsfunambulator** [VonOx/npp-pro#1]
Thanks for taking the time to write and upload this file.  Unfortunatly every time I open a config.pro file with the syntax highlighting file in Notepad++, it causes Notepad++ to crash!   It happend on my computer and a coworkers when he tried it.

Any idea what is wrong or how to fix this?

**Comment by VonOx** [comment]
Hi 

You use the latest version of Notepad++ **(6.7.3)** ?
I have not reproduce this issue.

Apologize for response delay

**Comment by Godsfunambulator** [comment]
I am using 6.5.3.

Unfortunately, upgrading is not exactly a simple process here, but since you have not reprodced this problem it sounds like that may be it so I wll try get it upgraded.  Thanks for the response and I will let you know how it goes..

**Comment by Ovalt1nejenk1ns** [comment]
I am having the same issue. When I set my language to PRO it crashes Notepad++

**Comment by VonOx** [comment]
Reproduce in latest version.

Try to fix ASAP

**Comment by Ovalt1nejenk1ns** [comment]
Thank you

**Comment by VonOx** [comment]
Hey

Can you confirm that the latest version does not crash N++ ?
